/* eslint-disable object-shorthand */
import { avatar } from '../assets';
import { TMessage, TUser, TUserPassword } from './types';

export const userProfileInfoData: TUser = {
  id: 123,
  first_name: 'Petya',
  second_name: 'Pupkin',
  display_name: 'Petya Pupkin',
  phone: '+79001001100',
  login: 'userLogin',
  avatar: avatar,
  email: 'string@ya.ru',
};

export const userProfilePasswordData: TUserPassword = {
  oldPassword: '•••••••••',
  newPassword: '•••••••••••',
};

export const messageContactsData: TMessage[] = [
  {
    id: 123,
    title: 'my-chat',
    avatar: avatar,
    unread_count: 0,
    created_by: 12345,
    last_message: {
      user: {
        first_name: 'Petya',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'string@ya.ru',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '12 Апр 2020',
      content: 'this is message content',
    },
  },
  {
    id: 124,
    title: 'Вадим',
    avatar: avatar,
    unread_count: 1,
    created_by: 12345,
    last_message: {
      user: {
        first_name: 'Petya',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '12 Апр 2020',
      content:
        'Привет! Смотри, тут всплыл интересный кусок лунной космической истории — НАСА в какой-то момент попросила Хассельблад адаптировать модель SWC для полетов на Луну. Сейчас мы все знаем что астронавты летали с моделью 500 EL — и к слову говоря, все тушки этих камер все еще находятся на поверхности Луны, так как астронавты с собой забрали только кассеты с пленкой. Хассельблад в итоге адаптировал SWC для космоса, но что-то пошло не так и на ракету они так никогда и не попали. Всего их было произведено 25 штук, одну из них недавно продали на аукционе за 45000 евро.',
    },
  },
  {
    id: 125,
    title: 'Андрей',
    avatar: avatar,
    unread_count: 0,
    created_by: 12345,
    last_message: {
      user: {
        first_name: 'Petya',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '12 Апр 2020',
      content: 'this is message content',
    },
  },
  {
    id: 126,
    title: 'my-chat',
    avatar: avatar,
    unread_count: 0,
    created_by: 12345,
    last_message: {
      user: {
        first_name: 'Petya',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'string@ya.ru',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '12 Апр 2020',
      content: 'this is message content',
    },
  },
  {
    id: 127,
    title: 'Вадим',
    avatar: avatar,
    unread_count: 1,
    created_by: 12345,
    last_message: {
      user: {
        first_name: 'Petya',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '12 Апр 2020',
      content:
        'Привет! Смотри, тут всплыл интересный кусок лунной космической истории — НАСА в какой-то момент попросила Хассельблад адаптировать модель SWC для полетов на Луну. Сейчас мы все знаем что астронавты летали с моделью 500 EL — и к слову говоря, все тушки этих камер все еще находятся на поверхности Луны, так как астронавты с собой забрали только кассеты с пленкой. Хассельблад в итоге адаптировал SWC для космоса, но что-то пошло не так и на ракету они так никогда и не попали. Всего их было произведено 25 штук, одну из них недавно продали на аукционе за 45000 евро.',
    },
  },
  {
    id: 128,
    title: 'Андрей',
    avatar: avatar,
    unread_count: 0,
    created_by: 12345,
    last_message: {
      user: {
        first_name: 'Petya',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'string@ya.ru',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '12 Апр 2020',
      content: 'this is message content',
    },
  },
  {
    id: 129,
    title: 'my-chat',
    avatar: avatar,
    unread_count: 15,
    created_by: 12345,
    last_message: {
      user: {
        first_name: 'Petya',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '12 Апр 2020',
      content: 'this is message content',
    },
  },
  {
    id: 130,
    title: 'Вадим',
    avatar: avatar,
    unread_count: 1,
    created_by: 12345,
    last_message: {
      user: {
        first_name: 'Petya',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '12 Апр 2020',
      content:
        'Привет! Смотри, тут всплыл интересный кусок лунной космической истории — НАСА в какой-то момент попросила Хассельблад адаптировать модель SWC для полетов на Луну. Сейчас мы все знаем что астронавты летали с моделью 500 EL — и к слову говоря, все тушки этих камер все еще находятся на поверхности Луны, так как астронавты с собой забрали только кассеты с пленкой. Хассельблад в итоге адаптировал SWC для космоса, но что-то пошло не так и на ракету они так никогда и не попали. Всего их было произведено 25 штук, одну из них недавно продали на аукционе за 45000 евро.',
    },
  },
  {
    id: 131,
    title: 'Андрей',
    avatar: avatar,
    unread_count: 0,
    created_by: 12345,
    last_message: {
      user: {
        first_name: 'Petya',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '12 Апр 2020',
      content: 'this is message content',
    },
  },
  {
    id: 132,
    title: 'my-chat',
    avatar: avatar,
    unread_count: 15,
    created_by: 12345,
    last_message: {
      user: {
        first_name: 'Petya',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '12 Апр 2020',
      content: 'this is message content',
    },
  },
  {
    id: 133,
    title: 'Вадим',
    avatar: avatar,
    unread_count: 1,
    created_by: 12345,
    last_message: {
      user: {
        first_name: 'Petya',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '12 Апр 2020',
      content:
        'Привет! Смотри, тут всплыл интересный кусок лунной космической истории — НАСА в какой-то момент попросила Хассельблад адаптировать модель SWC для полетов на Луну. Сейчас мы все знаем что астронавты летали с моделью 500 EL — и к слову говоря, все тушки этих камер все еще находятся на поверхности Луны, так как астронавты с собой забрали только кассеты с пленкой. Хассельблад в итоге адаптировал SWC для космоса, но что-то пошло не так и на ракету они так никогда и не попали. Всего их было произведено 25 штук, одну из них недавно продали на аукционе за 45000 евро.',
    },
  },
  {
    id: 134,
    title: 'Андрей',
    avatar: '',
    unread_count: 0,
    created_by: 12345,
    last_message: {
      user: {
        first_name: 'Petya',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '12 Апр 2020',
      content: 'this is message content',
    },
  },
  {
    id: 135,
    title: 'my-chat',
    avatar: '',
    unread_count: 15,
    created_by: 12345,
    last_message: {
      user: {
        first_name: 'Petya',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '12 Апр 2020',
      content: 'this is message content',
    },
  },
  {
    id: 136,
    title: 'Вадим',
    avatar: avatar,
    unread_count: 1,
    created_by: 12345,
    last_message: {
      user: {
        first_name: 'Petya',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '12 Апр 2020',
      content:
        'Привет! Смотри, тут всплыл интересный кусок лунной космической истории — НАСА в какой-то момент попросила Хассельблад адаптировать модель SWC для полетов на Луну. Сейчас мы все знаем что астронавты летали с моделью 500 EL — и к слову говоря, все тушки этих камер все еще находятся на поверхности Луны, так как астронавты с собой забрали только кассеты с пленкой. Хассельблад в итоге адаптировал SWC для космоса, но что-то пошло не так и на ракету они так никогда и не попали. Всего их было произведено 25 штук, одну из них недавно продали на аукционе за 45000 евро.',
    },
  },
  {
    id: 137,
    title: 'Андрей',
    avatar: '',
    unread_count: 0,
    created_by: 12345,
    last_message: {
      user: {
        first_name: 'Petya',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '12 Апр 2020',
      content: 'this is message content',
    },
  },
  {
    id: 138,
    title: 'my-chat',
    avatar: '',
    unread_count: 15,
    created_by: 12345,
    last_message: {
      user: {
        first_name: 'Petya',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '12 Апр 2020',
      content: 'this is message content',
    },
  },
  {
    id: 139,
    title: 'Вадим',
    avatar: '',
    unread_count: 1,
    created_by: 12345,
    last_message: {
      user: {
        first_name: 'Petya',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '12 Апр 2020',
      content:
        'Привет! Смотри, тут всплыл интересный кусок лунной космической истории — НАСА в какой-то момент попросила Хассельблад адаптировать модель SWC для полетов на Луну. Сейчас мы все знаем что астронавты летали с моделью 500 EL — и к слову говоря, все тушки этих камер все еще находятся на поверхности Луны, так как астронавты с собой забрали только кассеты с пленкой. Хассельблад в итоге адаптировал SWC для космоса, но что-то пошло не так и на ракету они так никогда и не попали. Всего их было произведено 25 штук, одну из них недавно продали на аукционе за 45000 евро.',
    },
  },
  {
    id: 140,
    title: 'Андрей',
    avatar: '',
    unread_count: 0,
    created_by: 12345,
    last_message: {
      user: {
        first_name: 'Petya',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '12 Апр 2020',
      content: 'this is message content',
    },
  },
];
